name: Push to Dockerhub
on:
  push:
    branches: [ master ]
jobs:
 push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: actions/checkout@v2
      - run: |
          NGINX_VERSION=$(curl -s 'http://nginx.org/en/download.html' | sed 's/</\'$'\n''</g' | sed -n '/>Stable version$/,$ p' | egrep -m1 -o '/download/nginx-.+\.tar\.gz' | sed 's/\/download\/nginx-//g' | sed 's/\.tar\.gz//g')
          echo "version_number=${NGINX_VERSION}" >> $GITHUB_ENV
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: yonggan/docker_nginx_modsecurity:latest
          build-args: NGINX_VERSION=${{ env.version_number }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
